### PR TITLE
Update to allow codecs to be specified via configuration

### PR DESCRIPTION
**Pull request by abe545**
Hi, so I needed the ability to pass the span as b3 headers, and this was the easiest way to unblock me. Please let me know if you'd like me to extend the json configuration to support specifying the codecs as well.

### CODE REVIEW

**Comment by riferrei** [comment]
I think that is fantastic! Thank you for contributing :+1:

**Comment by abe545** [comment]
> I think that is fantastic! Thank you for contributing 👍

Sweet, thanks! This project is exactly what I needed to get debezium traces working 😃

**Comment by riferrei** [comment]
Have you seen that I added support for Tracer Resolver in this implementation? So now people can instantiate their tracers with envVars. Check this example for Kafka Connect using Jaeger:

https://github.com/riferrei/the-song-is/blob/bef929e0733f91d0b96275080ae51a688d92a77c/terraform/util/kafka-connect.sh#L61

**Comment by riferrei** [comment]
That allows people using Zipkin to bring their own tracer resolver and make the tracer instantiation less programmatic and more configurable.

**Comment by abe545** [comment]
I hadn't seen that - but that is essentially how I'm doing it.

**Comment by riferrei** [comment]
Actually is a little different. The place where you changed means people are using the built-in way to instantiate Jaeger tracers using the support that is kind of proprietary to this interceptor. This other way doesn't require you to create a interceptors.json file and all the configuration can be set using envVars. The magic is all based on the tracer resolver implementation that you would have to put in the classpath in order to work.

**Comment by riferrei** [comment]
image

**Comment by riferrei** [comment]
If you look the logic of the interceptor, it first tries to see if a custom interceptors file was provided. If not, it tries to fetch the tracer from the resolver... which is what I would expect that 80% of people would do.

The custom interceptors file is useful when you want multiple services within one single JVM, as opposite to the tracer resolver strategy which creates one service for each JVM.

**Pull request merged**
